# Generated by Django 4.2.5 on 2023-09-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project_main_image_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
