# Generated by Django 4.2.5 on 2023-09-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, default='bg5.jpg', null=True, upload_to=''),
        ),
    ]
